[package]
name = "monsim"
version = "0.2.0"
edition = "2021"

[dependencies]
bcontext_macro = { path = "bcontext_macro" }
event_derive_macro = { path = "event_derive_macro" }
bitflags = "1.3.2"
tui = "0.19.0"
crossterm = "0.26.0"

[lib]
name =  "monsim"
path = "src/lib.rs"

[[bin]]
name = "monsim_tui"
path = "src/main.rs"
