[package]
name = "monsim"
version = "0.9.0"
edition = "2021"

[dependencies]
monsim_macros = { path = "monsim_macros" }
monsim_utils = { path = "monsim_utils"}
bitflags = "1.3.2"
tui = "0.19.0"
crossterm = "0.26.0"
const_format = { version = "0.2.30", optional = true }
chrono = { version = "0.4.24", optional = true }
max_size_vec = { version = "0.1.0" }

[lib]
name =  "monsim"
path = "src/lib.rs"

[[bin]]
name = "monsim_tui"
path = "src/main.rs"

[features]
default = []
debug = ["const_format", "chrono"]
