use super::{Type, Percent};

pub const INEFFECTIVE: Percent = Percent(0);
pub const NOT_VERY_EFFECTIVE: Percent = Percent(50);
pub const EFFECTIVE: Percent = Percent(100);
pub const SUPER_EFFECTIVE: Percent = Percent(200);

pub const EMPTY_LINE: &str = "";

/// Usage:
/// 
/// ```ignore
/// matchup!(Type1 against Type2);
/// matchup!(Type1 against Type2 / Type3);
/// ```
/// which returns the `Percent` modifier for using a `Type1` type attack on a pure `Type2` type monster or a `Type2/Type3` dual-type monster.
#[macro_export]
macro_rules! matchup {
    ($x: ident against $y:ident / $z:ident) => {
        type_matchup($x, $y) * type_matchup($x, $z)
    };
    ($x: ident against $y:ident) => {
        type_matchup($x, $y)
    };
}

pub const fn type_matchup(move_type: Type, target_type: Type) -> Percent {
    match (move_type, target_type) {
        (Type::Bug, Type::Bug) => EFFECTIVE,
        (Type::Bug, Type::Dark) => SUPER_EFFECTIVE,
        (Type::Bug, Type::Dragon) => EFFECTIVE,
        (Type::Bug, Type::Electric) => EFFECTIVE,
        (Type::Bug, Type::Fairy) => NOT_VERY_EFFECTIVE,
        (Type::Bug, Type::Fighting) => NOT_VERY_EFFECTIVE,
        (Type::Bug, Type::Fire) => NOT_VERY_EFFECTIVE,
        (Type::Bug, Type::Flying) => NOT_VERY_EFFECTIVE,
        (Type::Bug, Type::Ghost) => NOT_VERY_EFFECTIVE,
        (Type::Bug, Type::Grass) => SUPER_EFFECTIVE,
        (Type::Bug, Type::Ground) => EFFECTIVE,
        (Type::Bug, Type::Ice) => EFFECTIVE,
        (Type::Bug, Type::Poison) => NOT_VERY_EFFECTIVE,
        (Type::Bug, Type::Psychic) => SUPER_EFFECTIVE,
        (Type::Bug, Type::Normal) => EFFECTIVE,
        (Type::Bug, Type::Rock) => EFFECTIVE,
        (Type::Bug, Type::Steel) => NOT_VERY_EFFECTIVE,
        (Type::Bug, Type::Water) => EFFECTIVE,

        (Type::Dark, Type::Bug) => EFFECTIVE,
        (Type::Dark, Type::Dark) => NOT_VERY_EFFECTIVE,
        (Type::Dark, Type::Dragon) => EFFECTIVE,
        (Type::Dark, Type::Electric) => EFFECTIVE,
        (Type::Dark, Type::Fairy) => NOT_VERY_EFFECTIVE,
        (Type::Dark, Type::Fighting) => NOT_VERY_EFFECTIVE,
        (Type::Dark, Type::Fire) => EFFECTIVE,
        (Type::Dark, Type::Flying) => EFFECTIVE,
        (Type::Dark, Type::Ghost) => SUPER_EFFECTIVE,
        (Type::Dark, Type::Grass) => EFFECTIVE,
        (Type::Dark, Type::Ground) => EFFECTIVE,
        (Type::Dark, Type::Ice) => EFFECTIVE,
        (Type::Dark, Type::Poison) => EFFECTIVE,
        (Type::Dark, Type::Psychic) => SUPER_EFFECTIVE,
        (Type::Dark, Type::Normal) => EFFECTIVE,
        (Type::Dark, Type::Rock) => EFFECTIVE,
        (Type::Dark, Type::Steel) => EFFECTIVE,
        (Type::Dark, Type::Water) => EFFECTIVE,

        (Type::Dragon, Type::Bug) => EFFECTIVE,
        (Type::Dragon, Type::Dark) => EFFECTIVE,
        (Type::Dragon, Type::Dragon) => SUPER_EFFECTIVE,
        (Type::Dragon, Type::Electric) => EFFECTIVE,
        (Type::Dragon, Type::Fairy) => INEFFECTIVE,
        (Type::Dragon, Type::Fighting) => EFFECTIVE,
        (Type::Dragon, Type::Fire) => EFFECTIVE,
        (Type::Dragon, Type::Flying) => EFFECTIVE,
        (Type::Dragon, Type::Ghost) => EFFECTIVE,
        (Type::Dragon, Type::Grass) => EFFECTIVE,
        (Type::Dragon, Type::Ground) => EFFECTIVE,
        (Type::Dragon, Type::Ice) => EFFECTIVE,
        (Type::Dragon, Type::Poison) => EFFECTIVE,
        (Type::Dragon, Type::Psychic) => EFFECTIVE,
        (Type::Dragon, Type::Normal) => EFFECTIVE,
        (Type::Dragon, Type::Rock) => EFFECTIVE,
        (Type::Dragon, Type::Steel) => NOT_VERY_EFFECTIVE,
        (Type::Dragon, Type::Water) => EFFECTIVE,

        (Type::Electric, Type::Bug) => EFFECTIVE,
        (Type::Electric, Type::Dark) => EFFECTIVE,
        (Type::Electric, Type::Dragon) => NOT_VERY_EFFECTIVE,
        (Type::Electric, Type::Electric) => NOT_VERY_EFFECTIVE,
        (Type::Electric, Type::Fairy) => EFFECTIVE,
        (Type::Electric, Type::Fighting) => EFFECTIVE,
        (Type::Electric, Type::Fire) => EFFECTIVE,
        (Type::Electric, Type::Flying) => SUPER_EFFECTIVE,
        (Type::Electric, Type::Ghost) => EFFECTIVE,
        (Type::Electric, Type::Grass) => NOT_VERY_EFFECTIVE,
        (Type::Electric, Type::Ground) => INEFFECTIVE,
        (Type::Electric, Type::Ice) => EFFECTIVE,
        (Type::Electric, Type::Poison) => EFFECTIVE,
        (Type::Electric, Type::Psychic) => EFFECTIVE,
        (Type::Electric, Type::Normal) => EFFECTIVE,
        (Type::Electric, Type::Rock) => EFFECTIVE,
        (Type::Electric, Type::Steel) => EFFECTIVE,
        (Type::Electric, Type::Water) => SUPER_EFFECTIVE,

        (Type::Fairy, Type::Bug) => EFFECTIVE,
        (Type::Fairy, Type::Dark) => SUPER_EFFECTIVE,
        (Type::Fairy, Type::Dragon) => SUPER_EFFECTIVE,
        (Type::Fairy, Type::Electric) => EFFECTIVE,
        (Type::Fairy, Type::Fairy) => EFFECTIVE,
        (Type::Fairy, Type::Fighting) => SUPER_EFFECTIVE,
        (Type::Fairy, Type::Fire) => NOT_VERY_EFFECTIVE,
        (Type::Fairy, Type::Flying) => EFFECTIVE,
        (Type::Fairy, Type::Ghost) => EFFECTIVE,
        (Type::Fairy, Type::Grass) => EFFECTIVE,
        (Type::Fairy, Type::Ground) => EFFECTIVE,
        (Type::Fairy, Type::Ice) => EFFECTIVE,
        (Type::Fairy, Type::Poison) => EFFECTIVE,
        (Type::Fairy, Type::Psychic) => EFFECTIVE,
        (Type::Fairy, Type::Normal) => EFFECTIVE,
        (Type::Fairy, Type::Rock) => EFFECTIVE,
        (Type::Fairy, Type::Steel) => NOT_VERY_EFFECTIVE,
        (Type::Fairy, Type::Water) => EFFECTIVE,

        (Type::Fighting, Type::Bug) => NOT_VERY_EFFECTIVE,
        (Type::Fighting, Type::Dark) => SUPER_EFFECTIVE,
        (Type::Fighting, Type::Dragon) => EFFECTIVE,
        (Type::Fighting, Type::Electric) => EFFECTIVE,
        (Type::Fighting, Type::Fairy) => NOT_VERY_EFFECTIVE,
        (Type::Fighting, Type::Fighting) => EFFECTIVE,
        (Type::Fighting, Type::Fire) => EFFECTIVE,
        (Type::Fighting, Type::Flying) => NOT_VERY_EFFECTIVE,
        (Type::Fighting, Type::Ghost) => INEFFECTIVE,
        (Type::Fighting, Type::Grass) => EFFECTIVE,
        (Type::Fighting, Type::Ground) => EFFECTIVE,
        (Type::Fighting, Type::Ice) => SUPER_EFFECTIVE,
        (Type::Fighting, Type::Poison) => NOT_VERY_EFFECTIVE,
        (Type::Fighting, Type::Psychic) => NOT_VERY_EFFECTIVE,
        (Type::Fighting, Type::Normal) => SUPER_EFFECTIVE,
        (Type::Fighting, Type::Rock) => SUPER_EFFECTIVE,
        (Type::Fighting, Type::Steel) => EFFECTIVE,
        (Type::Fighting, Type::Water) => EFFECTIVE,

        (Type::Fire, Type::Bug) => SUPER_EFFECTIVE,
        (Type::Fire, Type::Dark) => EFFECTIVE,
        (Type::Fire, Type::Dragon) => NOT_VERY_EFFECTIVE,
        (Type::Fire, Type::Electric) => EFFECTIVE,
        (Type::Fire, Type::Fairy) => EFFECTIVE,
        (Type::Fire, Type::Fighting) => EFFECTIVE,
        (Type::Fire, Type::Fire) => NOT_VERY_EFFECTIVE,
        (Type::Fire, Type::Flying) => EFFECTIVE,
        (Type::Fire, Type::Ghost) => EFFECTIVE,
        (Type::Fire, Type::Grass) => SUPER_EFFECTIVE,
        (Type::Fire, Type::Ground) => EFFECTIVE,
        (Type::Fire, Type::Ice) => SUPER_EFFECTIVE,
        (Type::Fire, Type::Poison) => EFFECTIVE,
        (Type::Fire, Type::Psychic) => EFFECTIVE,
        (Type::Fire, Type::Normal) => EFFECTIVE,
        (Type::Fire, Type::Rock) => NOT_VERY_EFFECTIVE,
        (Type::Fire, Type::Steel) => SUPER_EFFECTIVE,
        (Type::Fire, Type::Water) => NOT_VERY_EFFECTIVE,

        (Type::Flying, Type::Bug) => SUPER_EFFECTIVE,
        (Type::Flying, Type::Dark) => EFFECTIVE,
        (Type::Flying, Type::Dragon) => EFFECTIVE,
        (Type::Flying, Type::Electric) => NOT_VERY_EFFECTIVE,
        (Type::Flying, Type::Fairy) => EFFECTIVE,
        (Type::Flying, Type::Fighting) => SUPER_EFFECTIVE,
        (Type::Flying, Type::Fire) => EFFECTIVE,
        (Type::Flying, Type::Flying) => EFFECTIVE,
        (Type::Flying, Type::Ghost) => EFFECTIVE,
        (Type::Flying, Type::Grass) => SUPER_EFFECTIVE,
        (Type::Flying, Type::Ground) => EFFECTIVE,
        (Type::Flying, Type::Ice) => EFFECTIVE,
        (Type::Flying, Type::Poison) => EFFECTIVE,
        (Type::Flying, Type::Psychic) => EFFECTIVE,
        (Type::Flying, Type::Normal) => EFFECTIVE,
        (Type::Flying, Type::Rock) => NOT_VERY_EFFECTIVE,
        (Type::Flying, Type::Steel) => NOT_VERY_EFFECTIVE,
        (Type::Flying, Type::Water) => EFFECTIVE,

        (Type::Ghost, Type::Bug) => EFFECTIVE,
        (Type::Ghost, Type::Dark) => NOT_VERY_EFFECTIVE,
        (Type::Ghost, Type::Dragon) => EFFECTIVE,
        (Type::Ghost, Type::Electric) => EFFECTIVE,
        (Type::Ghost, Type::Fairy) => EFFECTIVE,
        (Type::Ghost, Type::Fighting) => EFFECTIVE,
        (Type::Ghost, Type::Fire) => EFFECTIVE,
        (Type::Ghost, Type::Flying) => EFFECTIVE,
        (Type::Ghost, Type::Ghost) => SUPER_EFFECTIVE,
        (Type::Ghost, Type::Grass) => EFFECTIVE,
        (Type::Ghost, Type::Ground) => EFFECTIVE,
        (Type::Ghost, Type::Ice) => EFFECTIVE,
        (Type::Ghost, Type::Poison) => EFFECTIVE,
        (Type::Ghost, Type::Psychic) => SUPER_EFFECTIVE,
        (Type::Ghost, Type::Normal) => INEFFECTIVE,
        (Type::Ghost, Type::Rock) => EFFECTIVE,
        (Type::Ghost, Type::Steel) => EFFECTIVE,
        (Type::Ghost, Type::Water) => EFFECTIVE,

        (Type::Grass, Type::Bug) => NOT_VERY_EFFECTIVE,
        (Type::Grass, Type::Dark) => EFFECTIVE,
        (Type::Grass, Type::Dragon) => EFFECTIVE,
        (Type::Grass, Type::Electric) => EFFECTIVE,
        (Type::Grass, Type::Fairy) => EFFECTIVE,
        (Type::Grass, Type::Fighting) => EFFECTIVE,
        (Type::Grass, Type::Fire) => NOT_VERY_EFFECTIVE,
        (Type::Grass, Type::Flying) => NOT_VERY_EFFECTIVE,
        (Type::Grass, Type::Ghost) => EFFECTIVE,
        (Type::Grass, Type::Grass) => EFFECTIVE,
        (Type::Grass, Type::Ground) => SUPER_EFFECTIVE,
        (Type::Grass, Type::Ice) => EFFECTIVE,
        (Type::Grass, Type::Poison) => NOT_VERY_EFFECTIVE,
        (Type::Grass, Type::Psychic) => EFFECTIVE,
        (Type::Grass, Type::Normal) => EFFECTIVE,
        (Type::Grass, Type::Rock) => SUPER_EFFECTIVE,
        (Type::Grass, Type::Steel) => NOT_VERY_EFFECTIVE,
        (Type::Grass, Type::Water) => SUPER_EFFECTIVE,

        (Type::Ground, Type::Bug) => NOT_VERY_EFFECTIVE,
        (Type::Ground, Type::Dark) => EFFECTIVE,
        (Type::Ground, Type::Dragon) => EFFECTIVE,
        (Type::Ground, Type::Electric) => SUPER_EFFECTIVE,
        (Type::Ground, Type::Fairy) => EFFECTIVE,
        (Type::Ground, Type::Fighting) => EFFECTIVE,
        (Type::Ground, Type::Fire) => SUPER_EFFECTIVE,
        (Type::Ground, Type::Flying) => INEFFECTIVE,
        (Type::Ground, Type::Ghost) => EFFECTIVE,
        (Type::Ground, Type::Grass) => NOT_VERY_EFFECTIVE,
        (Type::Ground, Type::Ground) => SUPER_EFFECTIVE,
        (Type::Ground, Type::Ice) => EFFECTIVE,
        (Type::Ground, Type::Poison) => EFFECTIVE,
        (Type::Ground, Type::Psychic) => EFFECTIVE,
        (Type::Ground, Type::Normal) => EFFECTIVE,
        (Type::Ground, Type::Rock) => SUPER_EFFECTIVE,
        (Type::Ground, Type::Steel) => SUPER_EFFECTIVE,
        (Type::Ground, Type::Water) => EFFECTIVE,

        (Type::Ice, Type::Bug) => EFFECTIVE,
        (Type::Ice, Type::Dark) => EFFECTIVE,
        (Type::Ice, Type::Dragon) => SUPER_EFFECTIVE,
        (Type::Ice, Type::Electric) => EFFECTIVE,
        (Type::Ice, Type::Fairy) => EFFECTIVE,
        (Type::Ice, Type::Fighting) => EFFECTIVE,
        (Type::Ice, Type::Fire) => NOT_VERY_EFFECTIVE,
        (Type::Ice, Type::Flying) => SUPER_EFFECTIVE,
        (Type::Ice, Type::Ghost) => EFFECTIVE,
        (Type::Ice, Type::Grass) => SUPER_EFFECTIVE,
        (Type::Ice, Type::Ground) => SUPER_EFFECTIVE,
        (Type::Ice, Type::Ice) => NOT_VERY_EFFECTIVE,
        (Type::Ice, Type::Poison) => EFFECTIVE,
        (Type::Ice, Type::Psychic) => EFFECTIVE,
        (Type::Ice, Type::Normal) => EFFECTIVE,
        (Type::Ice, Type::Rock) => EFFECTIVE,
        (Type::Ice, Type::Steel) => NOT_VERY_EFFECTIVE,
        (Type::Ice, Type::Water) => NOT_VERY_EFFECTIVE,

        (Type::Poison, Type::Bug) => EFFECTIVE,
        (Type::Poison, Type::Dark) => EFFECTIVE,
        (Type::Poison, Type::Dragon) => EFFECTIVE,
        (Type::Poison, Type::Electric) => EFFECTIVE,
        (Type::Poison, Type::Fairy) => SUPER_EFFECTIVE,
        (Type::Poison, Type::Fighting) => EFFECTIVE,
        (Type::Poison, Type::Fire) => EFFECTIVE,
        (Type::Poison, Type::Flying) => EFFECTIVE,
        (Type::Poison, Type::Ghost) => NOT_VERY_EFFECTIVE,
        (Type::Poison, Type::Grass) => SUPER_EFFECTIVE,
        (Type::Poison, Type::Ground) => NOT_VERY_EFFECTIVE,
        (Type::Poison, Type::Ice) => EFFECTIVE,
        (Type::Poison, Type::Poison) => NOT_VERY_EFFECTIVE,
        (Type::Poison, Type::Psychic) => EFFECTIVE,
        (Type::Poison, Type::Normal) => EFFECTIVE,
        (Type::Poison, Type::Rock) => NOT_VERY_EFFECTIVE,
        (Type::Poison, Type::Steel) => INEFFECTIVE,
        (Type::Poison, Type::Water) => EFFECTIVE,

        (Type::Psychic, Type::Bug) => EFFECTIVE,
        (Type::Psychic, Type::Dark) => INEFFECTIVE,
        (Type::Psychic, Type::Dragon) => EFFECTIVE,
        (Type::Psychic, Type::Electric) => EFFECTIVE,
        (Type::Psychic, Type::Fairy) => EFFECTIVE,
        (Type::Psychic, Type::Fighting) => SUPER_EFFECTIVE,
        (Type::Psychic, Type::Fire) => EFFECTIVE,
        (Type::Psychic, Type::Flying) => EFFECTIVE,
        (Type::Psychic, Type::Ghost) => EFFECTIVE,
        (Type::Psychic, Type::Grass) => EFFECTIVE,
        (Type::Psychic, Type::Ground) => EFFECTIVE,
        (Type::Psychic, Type::Ice) => EFFECTIVE,
        (Type::Psychic, Type::Poison) => SUPER_EFFECTIVE,
        (Type::Psychic, Type::Psychic) => NOT_VERY_EFFECTIVE,
        (Type::Psychic, Type::Normal) => EFFECTIVE,
        (Type::Psychic, Type::Rock) => EFFECTIVE,
        (Type::Psychic, Type::Steel) => NOT_VERY_EFFECTIVE,
        (Type::Psychic, Type::Water) => EFFECTIVE,

        (Type::Normal, Type::Bug) => EFFECTIVE,
        (Type::Normal, Type::Dark) => EFFECTIVE,
        (Type::Normal, Type::Dragon) => EFFECTIVE,
        (Type::Normal, Type::Electric) => EFFECTIVE,
        (Type::Normal, Type::Fairy) => EFFECTIVE,
        (Type::Normal, Type::Fighting) => EFFECTIVE,
        (Type::Normal, Type::Fire) => EFFECTIVE,
        (Type::Normal, Type::Flying) => EFFECTIVE,
        (Type::Normal, Type::Ghost) => INEFFECTIVE,
        (Type::Normal, Type::Grass) => EFFECTIVE,
        (Type::Normal, Type::Ground) => EFFECTIVE,
        (Type::Normal, Type::Ice) => EFFECTIVE,
        (Type::Normal, Type::Poison) => EFFECTIVE,
        (Type::Normal, Type::Psychic) => EFFECTIVE,
        (Type::Normal, Type::Normal) => EFFECTIVE,
        (Type::Normal, Type::Rock) => NOT_VERY_EFFECTIVE,
        (Type::Normal, Type::Steel) => NOT_VERY_EFFECTIVE,
        (Type::Normal, Type::Water) => EFFECTIVE,

        (Type::Rock, Type::Bug) => SUPER_EFFECTIVE,
        (Type::Rock, Type::Dark) => EFFECTIVE,
        (Type::Rock, Type::Dragon) => EFFECTIVE,
        (Type::Rock, Type::Electric) => EFFECTIVE,
        (Type::Rock, Type::Fairy) => EFFECTIVE,
        (Type::Rock, Type::Fighting) => NOT_VERY_EFFECTIVE,
        (Type::Rock, Type::Fire) => SUPER_EFFECTIVE,
        (Type::Rock, Type::Flying) => SUPER_EFFECTIVE,
        (Type::Rock, Type::Ghost) => EFFECTIVE,
        (Type::Rock, Type::Grass) => EFFECTIVE,
        (Type::Rock, Type::Ground) => NOT_VERY_EFFECTIVE,
        (Type::Rock, Type::Ice) => SUPER_EFFECTIVE,
        (Type::Rock, Type::Poison) => EFFECTIVE,
        (Type::Rock, Type::Psychic) => EFFECTIVE,
        (Type::Rock, Type::Normal) => EFFECTIVE,
        (Type::Rock, Type::Rock) => EFFECTIVE,
        (Type::Rock, Type::Steel) => NOT_VERY_EFFECTIVE,
        (Type::Rock, Type::Water) => EFFECTIVE,

        (Type::Steel, Type::Bug) => EFFECTIVE,
        (Type::Steel, Type::Dark) => EFFECTIVE,
        (Type::Steel, Type::Dragon) => EFFECTIVE,
        (Type::Steel, Type::Electric) => NOT_VERY_EFFECTIVE,
        (Type::Steel, Type::Fairy) => SUPER_EFFECTIVE,
        (Type::Steel, Type::Fighting) => EFFECTIVE,
        (Type::Steel, Type::Fire) => NOT_VERY_EFFECTIVE,
        (Type::Steel, Type::Flying) => EFFECTIVE,
        (Type::Steel, Type::Ghost) => EFFECTIVE,
        (Type::Steel, Type::Grass) => EFFECTIVE,
        (Type::Steel, Type::Ground) => EFFECTIVE,
        (Type::Steel, Type::Ice) => SUPER_EFFECTIVE,
        (Type::Steel, Type::Poison) => EFFECTIVE,
        (Type::Steel, Type::Psychic) => EFFECTIVE,
        (Type::Steel, Type::Normal) => EFFECTIVE,
        (Type::Steel, Type::Rock) => SUPER_EFFECTIVE,
        (Type::Steel, Type::Steel) => NOT_VERY_EFFECTIVE,
        (Type::Steel, Type::Water) => NOT_VERY_EFFECTIVE,

        (Type::Water, Type::Bug) => EFFECTIVE,
        (Type::Water, Type::Dark) => EFFECTIVE,
        (Type::Water, Type::Dragon) => NOT_VERY_EFFECTIVE,
        (Type::Water, Type::Electric) => EFFECTIVE,
        (Type::Water, Type::Fairy) => EFFECTIVE,
        (Type::Water, Type::Fighting) => EFFECTIVE,
        (Type::Water, Type::Fire) => SUPER_EFFECTIVE,
        (Type::Water, Type::Flying) => EFFECTIVE,
        (Type::Water, Type::Ghost) => EFFECTIVE,
        (Type::Water, Type::Grass) => NOT_VERY_EFFECTIVE,
        (Type::Water, Type::Ground) => SUPER_EFFECTIVE,
        (Type::Water, Type::Ice) => EFFECTIVE,
        (Type::Water, Type::Poison) => EFFECTIVE,
        (Type::Water, Type::Psychic) => EFFECTIVE,
        (Type::Water, Type::Normal) => EFFECTIVE,
        (Type::Water, Type::Rock) => SUPER_EFFECTIVE,
        (Type::Water, Type::Steel) => EFFECTIVE,
        (Type::Water, Type::Water) => NOT_VERY_EFFECTIVE,
    }
}
